services:
  postgres:
    image: postgres:latest
    container_name: postgres_booking_system
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: booking_system
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
